server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Authx?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345689
jwt:
  secret: ZG9uZ3h1ZXFpbnF3ZXJ0eXVpb3Bsa2poZ2Zkc2F6eGN2Ym5t
  expiration: 7200000
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto